import type { Metadata } from 'next'
import { Inter, Lusitana } from 'next/font/google'
import localFont from 'next/font/local';
import './globals.css'

const bmJua = localFont({
    src: [{
        path: './font/BMJUA.otf',
        weight: 'normal',
        height: 'normal',
    }]
})

const inter = Inter({ subsets: ['latin'] })
const lusitana = Lusitana(
    { weight: ['400', '700'],
      subsets: ['latin']
    });
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={bmJua.className}>{children}</body>
    </html>
  )
}
